# Work with Python 3.6
import requests
import praw
import random
import asyncio
import aiohttp
import json
import discord
import os
import bs4
import PIL
from bs4 import BeautifulSoup
from discord import Game
from discord.ext.commands import Bot
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw, ImageOps

# pip install pipreqs
# pipreqs . --force
# git add . && git commit -m "minor change" && git push heroku master

BOT_PREFIX = ("!", "?")
TOKEN = os.environ.get("DISCORD_TOKEN")  # Get at discordapp.com/developers/applications/me

# From the Reddit API Page... (user_agent I made up)
reddit = praw.Reddit(client_id=os.environ.get('REDDIT_CLIENT_ID'),
                     client_secret=os.environ.get('REDDIT_SECRET'),
                     user_agent=os.environ.get('REDDIT_USER_AGENT'))

client = Bot(command_prefix=BOT_PREFIX)

@client.command(name='poke',
                description="Ask Worf how he feels today",
                brief="Let Worf tell you how he feels",
                aliases=['slap', 'push', '^'],
                pass_context=True)
async def eight_ball(context):
    possible_responses = [
        'Sir, I protest! I am NOT a merry man!',
        'Less talk! More synthehol!',
        'Congratulations. You are now fully dilated to ten centimeters. You may now give birth.',
        'Do not approach me unannounced—especially while I am eating.',
        'Good tea... nice house',
        'Die',
        'You will walk, or I will carry you.',
        'That is a joke. I get it. It is not funny, but I get it.',
        '... I will feed him.',
        'Prune Juice',
        'It is a cellular peptide cake.'
    ]
    await client.say(context.message.author.mention + " " + random.choice(possible_responses))

@client.command()
async def lifeforms():
    await client.say("https://www.youtube.com/watch?v=dWBmaKk32fE")
    await client.say("```RIKER: Any luck, Mister Worf?\nWORF: No sir. I still cannot locate the Captain.\nRIKER: The sensors still cannot penetrate the planet biosphere. There's too much interference. Can you find a way to scan for lifeforms?\nDATA: I would be happy to, sir. I just love scanning for lifeforms. ...'Life forms, ...you tiny little lifeforms, ...you precious little life forms, ...where are you.'```")


@client.command()
async def frf():
    await client.say("FRF is a secret organization that was established in Brantford, in April 1999, under the cover of a hydraulic and heavy equipment company, but in reality, it's a secret society of perverted people, who call themselves the Friendly Rabbit F**kers, hence the FRF! Our @dextersaintjocke#7194 is a founding member, and proudly wears his FRF jacket out in the open!")

@client.command()
async def people():
    await client.say(" dextersaintjocke: **MikeyJ**\n \
Adam Ferguson: **Adam**\n \
draalin: **Tyler**\n \
Drew: **Drew**\n \
elham: **Elham**\n \
Erick: **Erick**\n \
foozlereducer: **Steve**\n \
Goldfinger: **Goldwin**\n \
Hawkeye_IX: **Yul**\n \
J03: **Joe**\n \
Jenny: **Jenny**\n \
kblago: **KellyB**\n \
keleco: **KellyS**\n \
Keo: **Keith**\n \
Kyle: **Kyle**\n \
lailaB: **Laila**\n \
MMM: **Mo**\n \
mred9: **Ed**\n \
murphesi: **Chris**\n \
Pinkredible: **Lissa**\n \
Ted: **Ted**\n \
this_is_Aleah: **any guesses?**\n \
toddhdow: **Todd**\n \
waheez: **Waheed**\n \
wombat84: **Donnie**\n \
Zaptos_Lover: **Scott**\n")

@client.event
async def on_ready():
    await client.change_presence(game=Game(name="!help"))
    print("Logged in as " + client.user.name)

@client.command(name='crypto',
                description="Crypto Prices",
                brief="Crypto (Use bitcoin rather than btc)",
                aliases=['c', 'cryptocurrency'])
async def crypto(arg):
    url = 'https://api.coinmarketcap.com/v1/ticker/{}'.format(arg)
    response = requests.get(url)
    value = response.json()[0]["price_usd"]
    await client.say(arg.capitalize() +" is: $" + value + " USD")

@client.command(name='search',
                description="Memory Alpha Star Trek search",
                brief="Memory Alpha Trek Search",
                aliases=['s', 'ma'])
async def search(*, arg):
    url = 'http://memory-alpha.wikia.com/wiki/Special:Search?query={}'.format(arg).replace(" ","%20")
    # Grab first class="result-link" ahref
    # Use xpath

    # import requests
    # from bs4 import BeautifulSoup
    #url = 'http://memory-alpha.wikia.com/wiki/Special:Search?search=wolf+359&fulltext=Search&ns0=1&ns4=1#'
    page_response = requests.get(url, timeout=5)
    page_content = BeautifulSoup(page_response.content, "html.parser")
    result = page_content.find_all('a',class_='result-link')[1].text
    #print(paragraphs)

    #API Example
    # import requests
    # url ='http://memory-alpha.wikia.com/wiki/Special:Search?query=wolf+359/api.php?action=query&format=json'
    # resp = requests.get(url=url)
    # data = resp.json()
    # print(data[0])
    # {'title': 'Wolf', 'url': 'http://memory-alpha.wikia.com/wiki/Wolf', 'pageid': 32300}

    await client.say(result)

@client.command(name='chris',
                description="christie",
                brief="Take a look at Miss Postmedia!",
                aliases=['chrisina', 'christie'],
                pass_context=True)
async def chris(ctx, *, arg):
    im=Image.open("media/miss-postmedia.png")
    f = ImageFont.truetype("typography/FINALOLD.TTF", 50)
    txt=Image.new('L', (500,50))
    d = ImageDraw.Draw(txt)
    msg = "{}".format(arg)
    d.text( (20, 0),msg,  font=f, fill=255)
    w=txt.rotate(17.5,  expand=1)

    im.paste( ImageOps.colorize(w, (0,0,0), (255,255,84)), (20,150),  w)
    im.save('image.png')
    await client.send_file(ctx.message.channel, "image.png")

@client.command(name='startrekgif',
                description="A reddit Star Trek gif finder",
                brief="Random Star Trek memes",
                aliases=['stg', 'stgifs', 'stgif'],
                pass_context=True)
async def startrekgif():
    memes_submissions = reddit.subreddit('startrekgifs').hot()
    post_to_pick = random.randint(1, 10)
    for i in range(0, post_to_pick):
        submission = next(x for x in memes_submissions if not x.stickied)
    await client.say(submission.url)


@client.command(name='startrek',
                description="A reddit Star Trek meme finder",
                brief="Random Star Trek memes",
                aliases=['st', 'stmemes', 'vulcan'],
                pass_context=True)
async def startrek():
    memes_submissions = reddit.subreddit('startrekmemes').hot()
    post_to_pick = random.randint(1, 10)
    for i in range(0, post_to_pick):
        submission = next(x for x in memes_submissions if not x.stickied)
    await client.say(submission.url)

@client.command(name='wut',
                pass_context=True)
async def uglycats():
    memes_submissions = reddit.subreddit('awwwtf').top()
    post_to_pick = random.randint(1, 100)
    for i in range(0, post_to_pick):
        submission = next(x for x in memes_submissions if not x.stickied)
    await client.say(submission.url)

@client.command(name='episode',
                description="Suggest a random Star Trek episode",
                brief="Random Star Trek episode",
                aliases=['ep', 'show', 'epi'],
                pass_context=True)
async def episode(context):
    possible_responses = [
        'Pilot  0x00 - The Cage',
        'TOS - 1x01 - The Man Trap',
        'TOS - 1x02 - Charlie X',
        'TOS - 1x03 - Where No Man Has Gone Before',
        'TOS - 1x04 - The Naked Time',
        'TOS - 1x05 - The Enemy Within',
        'TOS - 1x06 - Mudd\'s Women',
        'TOS - 1x07 - What Are Little Girls Made Of?',
        'TOS - 1x08 - Miri',
        'TOS - 1x09 - Dagger of the Mind',
        'TOS - 1x10 - The Corbomite Maneuver',
        'TOS - 1x11 - The Menagerie (Part 1)',
        'TOS - 1x12 - The Menagerie (Part 2)',
        'TOS - 1x13 - The Conscience of the King',
        'TOS - 1x14 - Balance of Terror',
        'TOS - 1x15 - Shore Leave',
        'TOS - 1x16 - The Galileo Seven',
        'TOS - 1x17 - The Squire of Gothos',
        'TOS - 1x18 - Arena',
        'TOS - 1x19 - Tomorrow Is Yesterday',
        'TOS - 1x20 - Court Martial',
        'TOS - 1x21 - The Return of the Archons',
        'TOS - 1x22 - Space Seed',
        'TOS - 1x23 - A Taste of Armageddon',
        'TOS - 1x24 - This Side of Paradise',
        'TOS - 1x25 - The Devil in the Dark',
        'TOS - 1x26 - Errand of Mercy',
        'TOS - 1x27 - The Alternative Factor',
        'TOS - 1x28 - The City on the Edge of Forever',
        'TOS - 1x29 - Operation: Annihilate!',
        'TOS - 2x01 - Amok Time',
        'TOS - 2x02 - Who Mourns for Adonais?',
        'TOS - 2x03 - The Changeling',
        'TOS - 2x04 - Mirror, Mirror',
        'TOS - 2x05 - The Apple',
        'TOS - 2x06 - The Doomsday Machine',
        'TOS - 2x07 - Catspaw',
        'TOS - 2x08 - I, Mudd',
        'TOS - 2x09 - Metamorphosis',
        'TOS - 2x10 - Journey to Babel',
        'TOS - 2x11 - Friday\'s Child',
        'TOS - 2x12 - The Deadly Years',
        'TOS - 2x13 - Obsession',
        'TOS - 2x14 - Wolf in the Fold',
        'TOS - 2x15 - The Trouble with Tribbles',
        'TOS - 2x16 - The Gamesters of Triskelion',
        'TOS - 2x17 - A Piece of the Action',
        'TOS - 2x18 - The Immunity Syndrome',
        'TOS - 2x19 - A Private Little War',
        'TOS - 2x20 - Return to Tomorrow',
        'TOS - 2x21 - Patterns of Force',
        'TOS - 2x22 - By Any Other Name',
        'TOS - 2x23 - The Omega Glory',
        'TOS - 2x24 - The Ultimate Computer',
        'TOS - 2x25 - Bread and Circuses',
        'TOS - 2x26 - Assignment: Earth',
        'TOS - 3x01 - Spock\'s Brain',
        'TOS - 3x02 - The Enterprise Incident',
        'TOS - 3x03 - The Paradise Syndrome',
        'TOS - 3x04 - And the Children Shall Lead',
        'TOS - 3x05 - Is There in Truth No Beauty?',
        'TOS - 3x06 - Spectre of the Gun',
        'TOS - 3x07 - Day of the Dove',
        'TOS - 3x08 - For the World Is Hollow and I Have Touched the Sky',
        'TOS - 3x09 - The Tholian Web',
        'TOS - 3x10 - Plato\'s Stepchildren',
        'TOS - 3x11 - Wink of an Eye',
        'TOS - 3x12 - The Empath',
        'TOS - 3x13 - Elaan of Troyius',
        'TOS - 3x14 - Whom Gods Destroy',
        'TOS - 3x15 - Let That Be Your Last Battlefield',
        'TOS - 3x16 - The Mark of Gideon',
        'TOS - 3x17 - That Which Survives',
        'TOS - 3x18 - The Lights of Zetar',
        'TOS - 3x19 - Requiem for Methuselah',
        'TOS - 3x20 - The Way to Eden',
        'TOS - 3x21 - The Cloud Minders',
        'TOS - 3x22 - The Savage Curtain',
        'TOS - 3x23 - All Our Yesterdays',
        'TOS - 3x24 - Turnabout Intruder',
        'TAS - 1x01 - Beyond the Farthest Star',
        'TAS - 1x02 - Yesteryear',
        'TAS - 1x03 - One of Our Planets Is Missing',
        'TAS - 1x04 - The Lorelei Signal',
        'TAS - 1x05 - More Tribbles, More Troubles',
        'TAS - 1x06 - The Survivor',
        'TAS - 1x07 - The Infinite Vulcan',
        'TAS - 1x08 - The Magicks of Megas-Tu',
        'TAS - 1x09 - Once Upon a Planet',
        'TAS - 1x10 - Mudd\'s Passion',
        'TAS - 1x11 - The Terratin Incident',
        'TAS - 1x12 - The Time Trap',
        'TAS - 1x13 - The Ambergris Element',
        'TAS - 1x14 - The Slaver Weapon',
        'TAS - 1x15 - The Eye of the Beholder',
        'TAS - 1x16 - The Jihad',
        'TAS - 2x01 - The Pirates of Orion',
        'TAS - 2x02 - Bem',
        'TAS - 2x03 - The Practical Joker',
        'TAS - 2x04 - Albatross',
        'TAS - 2x05 - How Sharper Than a Serpent\'s Tooth',
        'TAS - 2x06 - The Counter-Clock Incident',
        'TOS Film   Film 1  Star Trek: The Motion Picture (1979)',
        'TOS Film   Film 2  Star Trek II: The Wrath of Khan (1982)',
        'TOS Film   Film 3  Star Trek III: The Search for Spock (1984)',
        'TOS Film   Film 4  Star Trek IV: The Voyage Home (1986)',
        'TOS Film   Film 5  Star Trek V: The Final Frontier (1989)',
        'TOS Film   Film 6  Star Trek VI: The Undiscovered Country (1991)',
        'TNG - 1x01 - Encounter at Farpoint',
        'TNG - 1x02 - The Naked Now',
        'TNG - 1x03 - Code of Honor',
        'TNG - 1x04 - The Last Outpost',
        'TNG - 1x05 - Where No One Has Gone Before',
        'TNG - 1x06 - Lonely Among Us',
        'TNG - 1x07 - Justice',
        'TNG - 1x08 - The Battle',
        'TNG - 1x09 - Hide and Q',
        'TNG - 1x10 - Haven',
        'TNG - 1x11 - The Big Goodbye',
        'TNG - 1x12 - Datalore',
        'TNG - 1x13 - Angel One',
        'TNG - 1x14 - 11001001',
        'TNG - 1x15 - Too Short a Season',
        'TNG - 1x16 - When The Bough Breaks',
        'TNG - 1x17 - Home Soil',
        'TNG - 1x18 - Coming of Age',
        'TNG - 1x19 - Heart of Glory',
        'TNG - 1x20 - The Arsenal of Freedom',
        'TNG - 1x21 - Symbiosis',
        'TNG - 1x22 - Skin of Evil',
        'TNG - 1x23 - We\'ll Always Have Paris',
        'TNG - 1x24 - Conspiracy',
        'TNG - 1x25 - The Neutral Zone',
        'TNG - 2x01 - The Child',
        'TNG - 2x02 - Where Silence Has Lease',
        'TNG - 2x03 - Elementary, Dear Data',
        'TNG - 2x04 - The Outrageous Okona',
        'TNG - 2x05 - Loud As A Whisper',
        'TNG - 2x06 - The Schizoid Man',
        'TNG - 2x07 - Unnatural Selection',
        'TNG - 2x08 - A Matter Of Honor',
        'TNG - 2x09 - The Measure Of A Man',
        'TNG - 2x10 - The Dauphin',
        'TNG - 2x11 - Contagion',
        'TNG - 2x12 - The Royale',
        'TNG - 2x13 - Time Squared',
        'TNG - 2x14 - The Icarus Factor',
        'TNG - 2x15 - Pen Pals',
        'TNG - 2x16 - Q Who',
        'TNG - 2x17 - Samaritan Snare',
        'TNG - 2x18 - Up The Long Ladder',
        'TNG - 2x19 - Manhunt',
        'TNG - 2x20 - The Emissary',
        'TNG - 2x21 - Peak Performance',
        'TNG - 2x22 - Shades of Gray',
        'TNG - 3x01 - Evolution',
        'TNG - 3x02 - The Ensigns of Command',
        'TNG - 3x03 - The Survivors',
        'TNG - 3x04 - Who Watches the Watchers',
        'TNG - 3x05 - The Bonding',
        'TNG - 3x06 - Booby Trap',
        'TNG - 3x07 - The Enemy',
        'TNG - 3x08 - The Price',
        'TNG - 3x09 - The Vengeance Factor',
        'TNG - 3x10 - The Defector',
        'TNG - 3x11 - The Hunted',
        'TNG - 3x12 - The High Ground',
        'TNG - 3x13 - Déja Q',
        'TNG - 3x14 - A Matter of Perspective',
        'TNG - 3x15 - Yesterday\'s Enterprise',
        'TNG - 3x16 - The Offspring',
        'TNG - 3x17 - Sins of the Father',
        'TNG - 3x18 - Allegiance',
        'TNG - 3x19 - Captain\'s Holiday',
        'TNG - 3x20 - Tin Man',
        'TNG - 3x21 - Hollow Pursuits',
        'TNG - 3x22 - The Most Toys',
        'TNG - 3x23 - Sarek',
        'TNG - 3x24 - Ménage a Troi',
        'TNG - 3x25 - Transfigurations',
        'TNG - 3x26 - The Best of Both Worlds Part 1',
        'TNG - 4x01 - The Best of Both Worlds, Part II',
        'TNG - 4x02 - Family',
        'TNG - 4x03 - Brothers',
        'TNG - 4x04 - Suddenly Human',
        'TNG - 4x05 - Remember Me',
        'TNG - 4x06 - Legacy',
        'TNG - 4x07 - Reunion',
        'TNG - 4x08 - Future Imperfect',
        'TNG - 4x09 - Final Mission',
        'TNG - 4x10 - The Loss',
        'TNG - 4x11 - Data\'s Day',
        'TNG - 4x12 - The Wounded',
        'TNG - 4x13 - Devil\'s Due',
        'TNG - 4x14 - Clues',
        'TNG - 4x15 - First Contact',
        'TNG - 4x16 - Galaxy\'s Child',
        'TNG - 4x17 - Night Terrors',
        'TNG - 4x18 - Identity Crisis',
        'TNG - 4x19 - The Nth Degree',
        'TNG - 4x20 - Qpid',
        'TNG - 4x21 - The Drumhead',
        'TNG - 4x22 - Half a Life',
        'TNG - 4x23 - The Host',
        'TNG - 4x24 - The Mind\'s Eye',
        'TNG - 4x25 - In Theory',
        'TNG - 4x26 - Redemption',
        'TNG - 5x01 - Redemption II',
        'TNG - 5x02 - Darmok',
        'TNG - 5x03 - Ensign Ro',
        'TNG - 5x04 - Silicon Avatar',
        'TNG - 5x05 - Disaster',
        'TNG - 5x06 - The Game',
        'TNG - 5x07 - Unification I',
        'TNG - 5x08 - Unification II',
        'TNG - 5x09 - A Matter of Time',
        'TNG - 5x10 - New Ground',
        'TNG - 5x11 - Hero Worship',
        'TNG - 5x12 - Violations',
        'TNG - 5x13 - The Masterpiece Society',
        'TNG - 5x14 - Conundrum',
        'TNG - 5x15 - Power Play',
        'TNG - 5x16 - Ethics',
        'TNG - 5x17 - The Outcast',
        'TNG - 5x18 - Cause and Effect',
        'TNG - 5x19 - The First Duty',
        'TNG - 5x20 - Cost of Living',
        'TNG - 5x21 - The Perfect Mate',
        'TNG - 5x22 - Imaginary Friend',
        'TNG - 5x23 - I Borg',
        'TNG - 5x24 - The Next Phase',
        'TNG - 5x25 - The Inner Light',
        'TNG - 5x26 - Time\'s Arrow',
        'TNG - 6x01 - Time\'s Arrow, Part II',
        'TNG - 6x02 - Realm of Fear',
        'TNG - 6x03 - Man of the People',
        'TNG - 6x04 - Relics',
        'TNG - 6x05 - Schisms',
        'TNG - 6x06 - True Q',
        'TNG - 6x07 - Rascals',
        'TNG - 6x08 - A Fistful of Datas',
        'TNG - 6x09 - The Quality of Life',
        'TNG - 6x10 - Chain of Command, Part I',
        'TNG - 6x11 - Chain of Command, Part II',
        'TNG - 6x12 - Ship in a Bottle',
        'TNG - 6x13 - Aquiel',
        'TNG - 6x14 - Face of the Enemy',
        'TNG - 6x15 - Tapestry',
        'TNG - 6x16 - Birthright, Part I',
        'TNG - 6x17 - Birthright, Part II',
        'TNG - 6x18 - Starship Mine',
        'TNG - 6x19 - Lessons',
        'TNG - 6x20 - The Chase',
        'TNG - 6x21 - Frame of Mind',
        'TNG - 6x22 - Suspicions',
        'TNG - 6x23 - Rightful Heir',
        'TNG - 6x24 - Second Chances',
        'TNG - 6x25 - Timescape',
        'TNG - 6x26 - Descent',
        'TNG - 7x01 - Descent, Part II',
        'TNG - 7x02 - Liaisons',
        'TNG - 7x03 - Interface',
        'TNG - 7x04 - Gambit, Part I',
        'TNG - 7x05 - Gambit, Part II',
        'TNG - 7x06 - Phantasms',
        'TNG - 7x07 - Dark Page',
        'TNG - 7x08 - Attached',
        'TNG - 7x09 - Force of Nature',
        'TNG - 7x10 - Inheritance',
        'TNG - 7x11 - Parallels',
        'TNG - 7x12 - The Pegasus',
        'TNG - 7x13 - Homeward',
        'TNG - 7x14 - Sub Rosa',
        'TNG - 7x15 - Lower Decks',
        'TNG - 7x16 - Thine Own Self',
        'TNG - 7x17 - Masks',
        'TNG - 7x18 - Eye of the Beholder',
        'TNG - 7x19 - Genesis',
        'TNG - 7x20 - Journey\'s End',
        'TNG - 7x21 - Firstborn',
        'TNG - 7x22 - Bloodlines',
        'TNG - 7x23 - Emergence',
        'TNG - 7x24 - Preemptive Strike',
        'TNG - 7x25/26 All Good Things...',
        'TNG Film   Film 1  Star Trek Generations',
        'TNG Film   Film 2  Star Trek: First Contact',
        'TNG Film   Film 3  Star Trek: Insurrection',
        'TNG Film   Film 4  Star Trek Nemesis',
        'DS9 - 1x01/02 Emissary',
        'DS9 - 1x03 - Past Prologue',
        'DS9 - 1x04 - A Man Alone',
        'DS9 - 1x05 - Babel',
        'DS9 - 1x06 - Captive Pursuit',
        'DS9 - 1x07 - Q-Less',
        'DS9 - 1x08 - Dax',
        'DS9 - 1x09 - The Passenger',
        'DS9 - 1x10 - Move Along Home',
        'DS9 - 1x11 - The Nagus',
        'DS9 - 1x12 - Vortex',
        'DS9 - 1x13 - Battle Lines',
        'DS9 - 1x14 - The Storyteller',
        'DS9 - 1x15 - Progress',
        'DS9 - 1x16 - If Wishes Were Horses',
        'DS9 - 1x17 - The Forsaken',
        'DS9 - 1x18 - Dramatis Personae',
        'DS9 - 1x19 - Duet',
        'DS9 - 1x20 - In the Hands of the Prophets',
        'DS9 - 2x01 - The Homecoming',
        'DS9 - 2x02 - The Circle',
        'DS9 - 2x03 - The Siege',
        'DS9 - 2x04 - Invasive Procedures',
        'DS9 - 2x05 - Cardassians',
        'DS9 - 2x06 - Melora',
        'DS9 - 2x07 - Rules of Acquisition',
        'DS9 - 2x08 - Necessary Evil',
        'DS9 - 2x09 - Second Sight',
        'DS9 - 2x10 - Sanctuary',
        'DS9 - 2x11 - Rivals',
        'DS9 - 2x12 - The Alternate',
        'DS9 - 2x13 - Armageddon Game',
        'DS9 - 2x14 - Whispers',
        'DS9 - 2x15 - Paradise',
        'DS9 - 2x16 - Shadowplay',
        'DS9 - 2x17 - Playing God',
        'DS9 - 2x18 - Profit and Loss',
        'DS9 - 2x19 - Blood Oath',
        'DS9 - 2x20 - The Maquis, Part I',
        'DS9 - 2x21 - The Maquis, Part II',
        'DS9 - 2x22 - The Wire',
        'DS9 - 2x23 - Crossover',
        'DS9 - 2x24 - The Collaborator',
        'DS9 - 2x25 - Tribunal',
        'DS9 - 2x26 - The Jem\'Hadar',
        'DS9 - 3x01 - The Search, Part I',
        'DS9 - 3x02 - The Search, Part II',
        'DS9 - 3x03 - The House of Quark',
        'DS9 - 3x04 - Equilibrium',
        'DS9 - 3x05 - Second Skin',
        'DS9 - 3x06 - The Abandoned',
        'DS9 - 3x07 - Civil Defense',
        'DS9 - 3x08 - Meridian',
        'DS9 - 3x09 - Defiant',
        'DS9 - 3x10 - Fascination',
        'DS9 - 3x11 - Past Tense, Part I',
        'DS9 - 3x12 - Past Tense, Part II',
        'DS9 - 3x13 - Life Support',
        'DS9 - 3x14 - Heart of Stone',
        'DS9 - 3x15 - Destiny',
        'DS9 - 3x16 - Prophet Motive',
        'DS9 - 3x17 - Visionary',
        'DS9 - 3x18 - Distant Voices',
        'DS9 - 3x19 - Through the Looking Glass',
        'DS9 - 3x20 - Improbable Cause',
        'DS9 - 3x21 - The Die is Cast',
        'DS9 - 3x22 - Explorers',
        'DS9 - 3x23 - Family Business',
        'DS9 - 3x24 - Shakaar',
        'DS9 - 3x25 - Facets',
        'DS9 - 3x26 - The Adversary',
        'DS9 - 4x01/02 The Way of the Warrior',
        'DS9 - 4x03 - The Visitor',
        'DS9 - 4x04 - Hippocratic Oath',
        'DS9 - 4x05 - Indiscretion',
        'DS9 - 4x06 - Rejoined',
        'DS9 - 4x07 - Starship Down',
        'DS9 - 4x08 - Little Green Men',
        'DS9 - 4x09 - The Sword of Kahless',
        'DS9 - 4x10 - Our Man Bashir',
        'DS9 - 4x11 - Homefront',
        'DS9 - 4x12 - Paradise Lost',
        'DS9 - 4x13 - Crossfire',
        'DS9 - 4x14 - Return to Grace',
        'DS9 - 4x15 - Sons of Mogh',
        'DS9 - 4x16 - Bar Association',
        'DS9 - 4x17 - Accession',
        'DS9 - 4x18 - Rules of Engagement',
        'DS9 - 4x19 - Hard Time',
        'DS9 - 4x20 - Shattered Mirror',
        'DS9 - 4x21 - The Muse',
        'DS9 - 4x22 - For the Cause',
        'DS9 - 4x23 - To the Death',
        'DS9 - 4x24 - The Quickening',
        'DS9 - 4x25 - Body Parts',
        'DS9 - 4x26 - Broken Link',
        'DS9 - 5x01 - Apocalypse Rising',
        'DS9 - 5x02 - The Ship',
        'DS9 - 5x03 - Looking for par\'Mach in All the Wrong Places',
        'DS9 - 5x04 - Nor the Battle to the Strong',
        'DS9 - 5x05 - The Assignment',
        'DS9 - 5x06 - Trials and Tribble-ations',
        'DS9 - 5x07 - Let He Who Is Without Sin...',
        'DS9 - 5x08 - Things Past',
        'DS9 - 5x09 - The Ascent',
        'DS9 - 5x10 - Rapture',
        'DS9 - 5x11 - The Darkness and the Light',
        'DS9 - 5x12 - The Begotten',
        'DS9 - 5x13 - For the Uniform',
        'DS9 - 5x14 - In Purgatory\'s Shadow',
        'DS9 - 5x15 - By Inferno\'s Light',
        'DS9 - 5x16 - Doctor Bashir, I Presume',
        'DS9 - 5x17 - A Simple Investigation',
        'DS9 - 5x18 - Business as Usual',
        'DS9 - 5x19 - Ties of Blood and Water',
        'DS9 - 5x20 - Ferengi Love Songs',
        'DS9 - 5x21 - Soldiers of the Empire',
        'DS9 - 5x22 - Children of Time',
        'DS9 - 5x23 - Blaze of Glory',
        'DS9 - 5x24 - Empok Nor',
        'DS9 - 5x25 - In the Cards',
        'DS9 - 5x26 - Call to Arms',
        'DS9 - 6x01 - A Time to Stand',
        'DS9 - 6x02 - Rocks and Shoals',
        'DS9 - 6x03 - Sons and Daughters',
        'DS9 - 6x04 - Behind the Lines',
        'DS9 - 6x05 - Favor the Bold',
        'DS9 - 6x06 - Sacrifice of Angels',
        'DS9 - 6x07 - You Are Cordially Invited',
        'DS9 - 6x08 - Resurrection',
        'DS9 - 6x09 - Statistical Probabilities',
        'DS9 - 6x10 - The Magnificent Ferengi',
        'DS9 - 6x11 - Waltz',
        'DS9 - 6x12 - Who Mourns for Morn?',
        'DS9 - 6x13 - Far Beyond the Stars',
        'DS9 - 6x14 - One Little Ship',
        'DS9 - 6x15 - Honor Among Thieves',
        'DS9 - 6x16 - Change of Heart',
        'DS9 - 6x17 - Wrongs Darker Than Death or Night',
        'DS9 - 6x18 - Inquisition',
        'DS9 - 6x19 - In the Pale Moonlight',
        'DS9 - 6x20 - His Way',
        'DS9 - 6x21 - The Reckoning',
        'DS9 - 6x22 - Valiant',
        'DS9 - 6x23 - Profit and Lace',
        'DS9 - 6x24 - Time\'s Orphan',
        'DS9 - 6x25 - The Sound of Her Voice',
        'DS9 - 6x26 - Tears of the Prophets',
        'DS9 - 7x01 - Image in the Sand',
        'DS9 - 7x02 - Shadows and Symbols',
        'DS9 - 7x03 - Afterimage',
        'DS9 - 7x04 - Take Me Out to the Holosuite',
        'DS9 - 7x05 - Chrysalis',
        'DS9 - 7x06 - Treachery, Faith and the Great River',
        'DS9 - 7x07 - Once More Unto the Breach',
        'DS9 - 7x08 - The Siege of AR-558',
        'DS9 - 7x09 - Covenant',
        'DS9 - 7x10 - It\'s Only a Paper Moon',
        'DS9 - 7x11 - Prodigal Daughter',
        'DS9 - 7x12 - The Emperor\'s New Cloak',
        'DS9 - 7x13 - Field of Fire',
        'DS9 - 7x14 - Chimera',
        'DS9 - 7x15 - Badda-Bing, Badda-Bang',
        'DS9 - 7x16 - Inter Arma Enim Silent Leges',
        'DS9 - 7x17 - Penumbra',
        'DS9 - 7x18 - Til Death Do Us Part',
        'DS9 - 7x19 - Strange Bedfellows',
        'DS9 - 7x20 - The Changing Face of Evil',
        'DS9 - 7x21 - When It Rains...',
        'DS9 - 7x22 - Tacking Into the Wind',
        'DS9 - 7x23 - Extreme Measures',
        'DS9 - 7x24 - The Dogs of War',
        'DS9 - 7x25/26 What You Leave Behind',
        'VOY - 1x01/02 Caretaker',
        'VOY - 1x03 - Parallax',
        'VOY - 1x04 - Time and Again',
        'VOY - 1x05 - Phage',
        'VOY - 1x06 - The Cloud',
        'VOY - 1x07 - Eye of the Needle',
        'VOY - 1x08 - Ex Post Facto',
        'VOY - 1x09 - Emanations',
        'VOY - 1x10 - Prime Factors',
        'VOY - 1x11 - State of Flux',
        'VOY - 1x12 - Heroes and Demons',
        'VOY - 1x13 - Cathexis',
        'VOY - 1x14 - Faces',
        'VOY - 1x15 - Jetrel',
        'VOY - 1x16 - Learning Curve',
        'VOY - 2x01 - The 37\'s',
        'VOY - 2x02 - Initiations',
        'VOY - 2x03 - Projections',
        'VOY - 2x04 - Elogium',
        'VOY - 2x05 - Non Sequitur',
        'VOY - 2x06 - Twisted',
        'VOY - 2x07 - Parturition',
        'VOY - 2x08 - Persistence of Vision',
        'VOY - 2x09 - Tattoo',
        'VOY - 2x10 - Cold Fire',
        'VOY - 2x11 - Maneuvers',
        'VOY - 2x12 - Resistance',
        'VOY - 2x13 - Prototype',
        'VOY - 2x14 - Alliances',
        'VOY - 2x15 - Threshold',
        'VOY - 2x16 - Meld',
        'VOY - 2x17 - Dreadnought',
        'VOY - 2x18 - Death Wish',
        'VOY - 2x19 - Lifesigns',
        'VOY - 2x20 - Investigations',
        'VOY - 2x21 - Deadlock',
        'VOY - 2x22 - Innocence',
        'VOY - 2x23 - The Thaw',
        'VOY - 2x24 - Tuvix',
        'VOY - 2x25 - Resolutions',
        'VOY - 2x26 - Basics, Part I',
        'VOY - 3x01 - Basics, Part II',
        'VOY - 3x02 - Flashback',
        'VOY - 3x03 - The Chute',
        'VOY - 3x04 - The Swarm',
        'VOY - 3x05 - False Profits',
        'VOY - 3x06 - Remember',
        'VOY - 3x07 - Sacred Ground',
        'VOY - 3x08 - Future\'s End',
        'VOY - 3x09 - Future\'s End, Part II',
        'VOY - 3x10 - Warlord',
        'VOY - 3x11 - The Q and the Grey',
        'VOY - 3x12 - Macrocosm',
        'VOY - 3x13 - Fair Trade',
        'VOY - 3x14 - Alter Ego',
        'VOY - 3x15 - Coda',
        'VOY - 3x16 - Blood Fever',
        'VOY - 3x17 - Unity',
        'VOY - 3x18 - Darkling',
        'VOY - 3x19 - Rise',
        'VOY - 3x20 - Favorite Son',
        'VOY - 3x21 - Before and After',
        'VOY - 3x22 - Real Life',
        'VOY - 3x23 - Distant Origin',
        'VOY - 3x24 - Displaced',
        'VOY - 3x25 - Worst Case Scenario',
        'VOY - 3x26 - Scorpion',
        'VOY - 4x01 - Scorpion, Part II',
        'VOY - 4x02 - The Gift',
        'VOY - 4x03 - Day of Honor',
        'VOY - 4x04 - Nemesis',
        'VOY - 4x05 - Revulsion',
        'VOY - 4x06 - The Raven',
        'VOY - 4x07 - Scientific Method',
        'VOY - 4x08 - Year of Hell',
        'VOY - 4x09 - Year of Hell, Part II',
        'VOY - 4x10 - Random Thoughts',
        'VOY - 4x11 - Concerning Flight',
        'VOY - 4x12 - Mortal Coil',
        'VOY - 4x13 - Waking Moments',
        'VOY - 4x14 - Message in a Bottle',
        'VOY - 4x15 - Hunters',
        'VOY - 4x16 - Prey',
        'VOY - 4x17 - Retrospect',
        'VOY - 4x18 - The Killing Game',
        'VOY - 4x19 - The Killing Game, Part II',
        'VOY - 4x20 - Vis à Vis',
        'VOY - 4x21 - The Omega Directive',
        'VOY - 4x22 - Unforgettable',
        'VOY - 4x23 - Living Witness',
        'VOY - 4x24 - Demon',
        'VOY - 4x25 - One',
        'VOY - 4x26 - Hope and Fear',
        'VOY - 5x01 - Night',
        'VOY - 5x02 - Drone',
        'VOY - 5x03 - Extreme Risk',
        'VOY - 5x04 - In the Flesh',
        'VOY - 5x05 - Once Upon a Time',
        'VOY - 5x06 - Timeless',
        'VOY - 5x07 - Infinite Regress',
        'VOY - 5x08 - Nothing Human',
        'VOY - 5x09 - Thirty Days',
        'VOY - 5x10 - Counterpoint',
        'VOY - 5x11 - Latent Image',
        'VOY - 5x12 - Bride of Chaotica!',
        'VOY - 5x13 - Gravity',
        'VOY - 5x14 - Bliss',
        'VOY - 5x15/16 Dark Frontier',
        'VOY - 5x17 - The Disease',
        'VOY - 5x18 - Course: Oblivion',
        'VOY - 5x19 - The Fight',
        'VOY - 5x20 - Think Tank',
        'VOY - 5x21 - Juggernaut',
        'VOY - 5x22 - Someone to Watch Over Me',
        'VOY - 5x23 - 11:59',
        'VOY - 5x24 - Relativity',
        'VOY - 5x25 - Warhead',
        'VOY - 5x26 - Equinox',
        'VOY - 6x01 - Equinox, Part II',
        'VOY - 6x02 - Survival Instinct',
        'VOY - 6x03 - Barge of the Dead',
        'VOY - 6x04 - Tinker Tenor Doctor Spy',
        'VOY - 6x05 - Alice',
        'VOY - 6x06 - Riddles',
        'VOY - 6x07 - Dragon\'s Teeth',
        'VOY - 6x08 - One Small Step',
        'VOY - 6x09 - The Voyager Conspiracy',
        'VOY - 6x10 - Pathfinder',
        'VOY - 6x11 - Fair Haven',
        'VOY - 6x12 - Blink of an Eye',
        'VOY - 6x13 - Virtuoso',
        'VOY - 6x14 - Memorial',
        'VOY - 6x15 - Tsunkatse',
        'VOY - 6x16 - Collective',
        'VOY - 6x17 - Spirit Folk',
        'VOY - 6x18 - Ashes to Ashes',
        'VOY - 6x19 - Child\'s Play',
        'VOY - 6x20 - Good Shepherd',
        'VOY - 6x21 - Live Fast and Prosper',
        'VOY - 6x22 - Muse',
        'VOY - 6x23 - Fury',
        'VOY - 6x24 - Life Line',
        'VOY - 6x25 - The Haunting of Deck Twelve',
        'VOY - 6x26 - Unimatrix Zero',
        'VOY - 7x01 - Unimatrix Zero, Part II',
        'VOY - 7x02 - Imperfection',
        'VOY - 7x03 - Drive',
        'VOY - 7x04 - Repression',
        'VOY - 7x05 - Critical Care',
        'VOY - 7x06 - Inside Man',
        'VOY - 7x07 - Body and Soul',
        'VOY - 7x08 - Nightingale',
        'VOY - 7x09/10 Flesh and Blood',
        'VOY - 7x11 - Shattered',
        'VOY - 7x12 - Lineage',
        'VOY - 7x13 - Repentance',
        'VOY - 7x14 - Prophecy',
        'VOY - 7x15 - The Void',
        'VOY - 7x16 - Workforce',
        'VOY - 7x17 - Workforce, Part II',
        'VOY - 7x18 - Human Error',
        'VOY - 7x19 - Q2',
        'VOY - 7x20 - Author, Author',
        'VOY - 7x21 - Friendship One',
        'VOY - 7x22 - Natural Law',
        'VOY - 7x23 - Homestead',
        'VOY - 7x24 - Renaissance Man',
        'VOY - 7x25/26 Endgame',
        'ENT - 1x01/02 Broken Bow',
        'ENT - 1x03 - Fight or Flight',
        'ENT - 1x04 - Strange New World',
        'ENT - 1x05 - Unexpected',
        'ENT - 1x06 - Terra Nova',
        'ENT - 1x07 - The Andorian Incident',
        'ENT - 1x08 - Breaking the Ice',
        'ENT - 1x09 - Civilization',
        'ENT - 1x10 - Fortunate Son',
        'ENT - 1x11 - Cold Front',
        'ENT - 1x12 - Silent Enemy',
        'ENT - 1x13 - Dear Doctor',
        'ENT - 1x14 - Sleeping Dogs',
        'ENT - 1x15 - Shadows of P\'Jem',
        'ENT - 1x16 - Shuttlepod One',
        'ENT - 1x17 - Fusion',
        'ENT - 1x18 - Rogue Planet',
        'ENT - 1x19 - Acquisition',
        'ENT - 1x20 - Oasis',
        'ENT - 1x21 - Detained',
        'ENT - 1x22 - Vox Sola',
        'ENT - 1x23 - Fallen Hero',
        'ENT - 1x24 - Desert Crossing',
        'ENT - 1x25 - Two Days and Two Nights',
        'ENT - 1x26 - Shockwave',
        'ENT - 2x01 - Shockwave, Part II',
        'ENT - 2x02 - Carbon Creek',
        'ENT - 2x03 - Minefield',
        'ENT - 2x04 - Dead Stop',
        'ENT - 2x05 - A Night in Sickbay',
        'ENT - 2x06 - Marauders',
        'ENT - 2x07 - The Seventh',
        'ENT - 2x08 - The Communicator',
        'ENT - 2x09 - Singularity',
        'ENT - 2x10 - Vanishing Point',
        'ENT - 2x11 - Precious Cargo',
        'ENT - 2x12 - The Catwalk',
        'ENT - 2x13 - Dawn',
        'ENT - 2x14 - Stigma',
        'ENT - 2x15 - Cease Fire',
        'ENT - 2x16 - Future Tense',
        'ENT - 2x17 - Canamar',
        'ENT - 2x18 - The Crossing',
        'ENT - 2x19 - Judgment',
        'ENT - 2x20 - Horizon',
        'ENT - 2x21 - The Breach',
        'ENT - 2x22 - Cogenitor',
        'ENT - 2x23 - Regeneration',
        'ENT - 2x24 - First Flight',
        'ENT - 2x25 - Bounty',
        'ENT - 2x26 - The Expanse',
        'ENT - 3x01 - The Xindi',
        'ENT - 3x02 - Anomaly',
        'ENT - 3x03 - Extinction',
        'ENT - 3x04 - Rajiin',
        'ENT - 3x05 - Impulse',
        'ENT - 3x06 - Exile',
        'ENT - 3x07 - The Shipment',
        'ENT - 3x08 - Twilight',
        'ENT - 3x09 - North Star',
        'ENT - 3x10 - Similitude',
        'ENT - 3x11 - Carpenter Street',
        'ENT - 3x12 - Chosen Realm',
        'ENT - 3x13 - Proving Ground',
        'ENT - 3x14 - Stratagem',
        'ENT - 3x15 - Harbinger',
        'ENT - 3x16 - Doctor\'s Orders',
        'ENT - 3x17 - Hatchery',
        'ENT - 3x18 - Azati Prime',
        'ENT - 3x19 - Damage',
        'ENT - 3x20 - The Forgotten',
        'ENT - 3x21 - E²',
        'ENT - 3x22 - The Council',
        'ENT - 3x23 - Countdown',
        'ENT - 3x24 - Zero Hour',
        'ENT - 4x01 - Storm Front',
        'ENT - 4x02 - Storm Front, Part II',
        'ENT - 4x03 - Home',
        'ENT - 4x04 - Borderland',
        'ENT - 4x05 - Cold Station 12',
        'ENT - 4x06 - The Augments',
        'ENT - 4x07 - The Forge',
        'ENT - 4x08 - Awakening',
        'ENT - 4x09 - Kir\'Shara',
        'ENT - 4x10 - Daedalus',
        'ENT - 4x11 - Observer Effect',
        'ENT - 4x12 - Babel One',
        'ENT - 4x13 - United',
        'ENT - 4x14 - The Aenar',
        'ENT - 4x15 - Affliction',
        'ENT - 4x16 - Divergence',
        'ENT - 4x17 - Bound',
        'ENT - 4x18 - In a Mirror, Darkly',
        'ENT - 4x19 - In a Mirror, Darkly, Part II',
        'ENT - 4x20 - Demons',
        'ENT - 4x21 - Terra Prime',
        'ENT - 4x22 - These Are the Voyages...',
        'Film   1   Star Trek',
        'Film   3   Star Trek Beyond',
        'DSC - 1x01 - The Vulcan Hello',
        'DSC - 1x02 - Battle at the Binary Stars',
        'DSC - 1x03 - Context Is for Kings',
        'DSC - 1x04 - The Butcher\'s Knife Cares Not for the Lamb\'s Cry',
        'DSC - 1x05 - Choose Your Pain',
        'DSC - 1x06 - Lethe',
        'DSC - 1x07 - Magic to Make the Sanest Man Go Mad',
        'DSC - 1x08 - Si Vis Pacem, Para Bellum',
        'DSC - 1x09 - Into the Forest I Go',
        'DSC - 1x10 - Despite Yourself',
        'DSC - 1x11 - The Wolf Inside',
        'DSC - 1x12 - Vaulting Ambition',
        'DSC - 1x13 - What\'s Past Is Prologue',
        'DSC - 1x14 - The War Without, The War Within',
        'DSC - 1x15 - Will You Take My Hand?'
    ]
    await client.say(context.message.author.mention + " I command you to watch " + random.choice(possible_responses))

async def list_servers():
    await client.wait_until_ready()
    while not client.is_closed:
        print("Current servers:")
        for server in client.servers:
            print(server.name)
        await asyncio.sleep(600)

client.loop.create_task(list_servers())

@client.event
async def on_member_join(member):
    server = member.server
    fmt = 'Hey @everyone... {0.mention} decided to finally show up. Try keep trash talk about them to DMs now.'
    await client.send_message(server, fmt.format(member, server))

@client.command(pass_context=True)
async def invite(ctx):
        invitelinknew = await client.create_invite(destination = ctx.message.channel, xkcd = True, max_uses = 100)
        embedMsg=discord.Embed(color=0xff0000)
        embedMsg.add_field(name="Invite Link", value=invitelinknew)
        embedMsg.set_footer(text="Copy the link above and send it to.... the hew-mon")
        await client.send_message(ctx.message.channel, embed=embedMsg)

client.run(TOKEN)